agent:
  label: cpp
  container: rickywraith/centos-devtools:latest
pipelines:
  pullRequest:
    build_cmake:
      steps:
      - sh: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
        name: cmake
    build_make:
      steps:
        - dir: build
          steps:
          - sh: make install
          name: make
    test:
      steps:
      - sh: ./tests/cxx_11_tests
        name: test_cpp_11
      - sh: ./tests/cxx_98_tests
        name: test_cpp_98
    container_build:
      steps:
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: ./charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview
    post:
      steps:
      - groovy: always
        when: "!prow"
        steps:
          - groovy: "cleanWs()"
  release:
     setup:
      steps:
      - groovy: git 'https://REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME.git'
        when: "prow"
      - sh: git checkout master
        comment: ensure we're not on a detached head
        when: "!prow"
      - sh: git config --global credential.helper store
        when: "!prow"
      - sh: jx step git credentials
        when: "!prow"
     setVersion:
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        name: next-version
        comment: so we can retrieve the version in later steps
      - sh: jx step tag --version \$(cat VERSION)
        name: tag-version
     build_make:
      steps:
        - dir: build
          steps:
          - sh: make install
          name: make
     test:
      steps:
      - sh: ./tests/cxx_11_tests
        name: test_cpp_11
      - sh: ./tests/cxx_98_tests
        name: test_cpp_98
     container_build:
      steps:
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
     postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
     promote:
      steps:
      - dir: ./charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote
     post:
      steps:
      - groovy: always
        when: "!prow"
        steps:
          - groovy: "cleanWs()"

